- name: install firewall
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tags:
     - firewall-config
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: Disable IPv6
      sysctl: name={{ item }} value=1 state=present
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: install iptables-persistent
      apt: name={{item}} state=installed
      with_items:
           - iptables-persistent
           - netfilter-persistent

    - name: bootstrap iptables persistence
      raw: service netfilter-persistent save

    - template: src=templates/iptables.j2 dest=/etc/iptables/rules.v4

    - name: load the iptable
      raw: iptables-restore < /etc/iptables/rules.v4